### ISSUE TITLE
[Data Visualization Widget] SECRET_KEY?

### ISSUE THREAD

**Issue by niicojs** [lumapps/samples#1]
Hi,

I'm trying to use the Data Visualizationn Widget at `samples/Data Visualization Widget/python/main.py`.
I can see the headers coming in, but I can't find where do you get the `SECRET_KEY` to verify that it's really coming from Lumapps.
I've looked in the docs, in admin and in the PowerPoint linked in main readme.

Thanks in advance

**Comment by jssevestre** [comment]
Hello, 

the SECRET_KEY is set on the customer configuration in LumApps by LumApps.
 
Please contact support@lumapps.com to request a secret key for our customer
